# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8adf58135c8b5fa8d50fec23c7b3396aa2b15fbddf6a17df59d7cfadb943fcd40448095d664ebca67e91ad13641624db47274a5593536072c54a9d9d38751249

test:
  secret_key_base: 396b9aca7f2deb2e20dd57072ee5eb6166e954a9f392c3ff59c333caf2be1d23e08abbece4d33e2d74e1dd36e39ef3b0a784bca7bf9ba3ba3603a9e3e4e26a5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
